### ISSUE TITLE
Develop a subscription snippet to subscribe to the FOSSASIA newsletter making use of the Sendy

### ISSUE THREAD

**Issue by mariobehling** [fossasia/unesco.sciencehack.asia#1]
**Objective**

Implement the FOSSASIA newsletter to work with Sendy.co. The goal is to substitute the current implementation with Mailchimp/Campaign Monitor (here: http://fossasia.org/#subscribe) with a self-hosted implementation.

Example snippet:

```
<form action="http://news.fossasia.org/subscribe" method="POST" accept-charset="utf-8">
    <label for="name">Name</label><br/>
    <input type="text" name="name" id="name"/>
    <br/>
    <label for="email">Email</label><br/>
    <input type="text" name="email" id="email"/>
    <br/>
    <input type="hidden" name="list" value="A8fchTRvBw2wap1ojIfjyQ"/>
    <input type="submit" name="submit" id="submit"/>
</form>
```

**More Info/Requirements**
- Use https://sendy.co
- In case you need the documentation of the API, it is here: https://sendy.co/api
- Repository http://fossasia.github.io/fossasia-subscriptions

**Expected Outcome:**
- Code Clean up
- Simple code, that can be copy/pasted
- Implementation works on Github Pages
- Document how designers can add code

**Comment by mariobehling** [comment]
Here is a snippet that can be used
```
<form action="http://news.fossasia.org/subscribe" method="POST" accept-charset="utf-8">
	<label for="name">Name</label><br/>
	<input type="text" name="name" id="name"/>
	<br/>
	<label for="email">Email</label><br/>
	<input type="text" name="email" id="email"/>
	<br/>
	<input type="hidden" name="list" value="A8fchTRvBw2wap1ojIfjyQ"/>
	<input type="submit" name="submit" id="submit"/>
</form>
```

**Comment by Juanvulcano** [comment]
The implementation must work with Github pages. 
I found on the web that since Github Pages is not a full-featured web host, it will not execute PHP or any other arbitrary code. 
Sendy examples use PHP and node.js, what can I use for this task?

**Comment by mariobehling** [comment]
The example snippet already works on github, but we need it to work with the design in index.html.

Example snippet:
```
<form action="http://news.fossasia.org/subscribe" method="POST" accept-charset="utf-8">
    <label for="name">Name</label><br/>
    <input type="text" name="name" id="name"/>
    <br/>
    <label for="email">Email</label><br/>
    <input type="text" name="email" id="email"/>
    <br/>
    <input type="hidden" name="list" value="A8fchTRvBw2wap1ojIfjyQ"/>
    <input type="submit" name="submit" id="submit"/>
</form>
```

**Comment by alan-aipe** [comment]
<b>@mariobehling</b> 
I would like to work on this issue and implement the feature. Can I?

**Comment by alan-aipe** [comment]
For implementing, I would need the sendy API installation URL for fossasia and link to the source code of news.fossasia.org/subscribe to display the correct result. @mariobehling

**Comment by mariobehling** [comment]
Hi @alan-aipe , I think @Juanvulcano already solved this issue now. Do you have any suggestions for improvements? Or what you would do differently?

**Comment by alan-aipe** [comment]
@mariobehling 
I guess I can improve it by adding a verify-email API to index.html. This will reduce fake registration as well as space optimization. 
More info on verify-mail : http://verify-email.org/
More Info on implementation of  the API : http://verify-email.org/using-api.html

If you think this is feasible and good, I would like to do it

**Comment by mariobehling** [comment]
Nice, looks good to me. Thank you.

**Comment by alan-aipe** [comment]
Shall I start implementing it?

**Comment by mariobehling** [comment]
Alternatively, is there a simple option just to check that all fields were entered and that there is a real email? I think the suggested service is nice, but it increases dependencies on other sites and we would give them all emails that are subscribed to us even if they say, they do not save them. We do not know really, if they do or not.
