### ISSUE TITLE
Add guest speakers & mentors

### ISSUE THREAD

**Issue by edenyay** [fossasia/unesco.sciencehack.asia#53]
Sofian Akmal Abd. Karim
Consul General of Malaysia
Embassy of Malaysia

![images1508392_6b](https://user-images.githubusercontent.com/32028823/46060600-1f554980-c18e-11e8-8f49-a646b34cdfc3.jpg)

**Comment by edenyay** [comment]
(mentor)
![longnguyen](https://user-images.githubusercontent.com/32028823/46081819-a83ca700-c1c7-11e8-9ddd-d717f28ff0b1.jpg)

Long Nguyen
Principal Software Engineer
BodiData Inc

**Comment by edenyay** [comment]
Hai Nguyen
????
StarUp.vn & FinHome.com


![hainguyen](https://user-images.githubusercontent.com/32028823/46085392-24d38380-c1d0-11e8-9acd-a6fdd9006c86.jpg)

**Comment by trungbanh** [comment]
i done it #54

**Comment by edenyay** [comment]
(jury)

![chongwaikit](https://user-images.githubusercontent.com/32028823/46127743-cbb13180-c25b-11e8-920f-95d3f1fc2875.jpg)

Chong Wai Kit
Consul of Education 
Embassy of Malaysia

**Comment by edenyay** [comment]
(mentor)

![lorem ipsum dolor sit amet adipiscing elit sed diam nummy 12](https://user-images.githubusercontent.com/32028823/46188213-fcec3900-c311-11e8-9f7a-4acf33c39ccb.png)

Mi Hoang
Lecturer 
University of Economics and Finance
